language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t maxfnine/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true maxfnine/react-test npm run test -- --coverage

after_success:
  - docker build -t maxfnine/multi-client ./client
  - docker build -t maxfnine/multi-nginx ./nginx
  - docker build -t maxfnine/multi-server ./server
  - docker build -t maxfnine/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push maxfnine/multi-client
  - docker push maxfnine/multi-nginx
  - docker push maxfnine/multi-server
  - docker push maxfnine/multi-worker
